### ISSUE TITLE
Sauvegarder CDS en texte

### ISSUE THREAD

**Issue by Pawamoy** [Pawamoy/CriCriStatistics#1]
L'utilisateur doit pouvoir demander à sauvegarder les données (séquence entière d'un génome) dans des fichiers textes (d'après le sujet). Par défaut non sauvegardés car ça prend beaucoup de place.

**Comment by pallamidessi** [comment]
Thomas peut le raoidement, il suffit d'écrire les différents scanners sur le disque.

**Comment by Pawamoy** [comment]
J'ai ajouté ce qu'il faut dans les settings:

    if (settings.savingData()) { /* write file */ }
