### ISSUE TITLE
Stats groupées

### ISSUE THREAD

**Issue by Pawamoy** [Pawamoy/CriCriStatistics#10]
On devrait en fait relire les fichiers Excel pour le calcul des stats groupées (désolé Mad :disappointed:).
En effet si on lance le programme une première fois, les stats groupées seront correctes (et ce même si on arrête et redémarre le traitement, car StatsFactory n'est pas vidée).
En revanche si on ferme le programme et qu'on le relance, alors les ArrayLists de StatsFactory sont réinitialisés, et on y ajoute **seulement** les nouvelles données traitées (et pas celles déjà indexées dans la BDD), donc les stats groupées deviennent fausses.

Il faudrait totalement séparer les processus de stats et de stats groupées (qu'on déclencherait comme maintenant à la fermeture du programme et/ou avec un bouton de l'interface graphique).

Si vous pensez qu'on a le temps je me met direct au code de lecture des fichiers, il restera alors juste à initialiser les arraylist de StatsFactory avec les données lues, et ne plus l'appeler depuis le parser.

**Comment by pallamidessi** [comment]
Yep, faut absolument faire ça !
