### ISSUE TITLE
Mise à jour des données modifiées

### ISSUE THREAD

**Issue by Pawamoy** [Pawamoy/CriCriStatistics#4]
Utiliser les données temporelles des fichiers téléchargés pour comparer avec ceux déjà traités ?
Stocker la dernière date dans la BDD au lieu de "XXXXX" ?

**Comment by pallamidessi** [comment]
Pas moyen d'avoir une date de dernière mise à jour coté genbank, donc on a pas de moyen de savoir ce qui a changé entre deux runs.
