### ISSUE TITLE
Fonctionnalité "statistique massive"

### ISSUE THREAD

**Issue by Pawamoy** [Pawamoy/CriCriStatistics#5]
Sujet:

> Proposer une fonctionnalité "statistique massive" comprenant toutes les données et une fonctionnalité "statistique fine" qui ne traite pas les doublons génomiques (uniquement un bioproject).

**Comment by Pawamoy** [comment]
Si quelqu'un a capté ce qui est demandé, peut-il expliquer ? :wheelchair:

**Comment by pallamidessi** [comment]
Pas le temps d'implémenter ça, anyway :x .
